### ISSUE TITLE
Question about Dataset

### ISSUE THREAD

**Issue by lsrock1** [tstafylakis/Lipreading-ResNet#2]
Thank you for sharing your awesome result. I have a question about the dataset.
In readme landmark detection section, you said the faces are already centered. What does that mean? BBC data are not centered and your gen.lua code doesnt have any centering function. Do you mean preprocessed data that are in gen directory are already centered?
If so, could you upload your landmark detection code?

**Comment by tstafylakis** [comment]
Hi,
I refer to the LRW dataset (Please see the link in [1]). Faces are already centered as clearly explained by the creators of the database ("For each of the occurrences, the one-second clip is taken, and the face is cropped with the mouth centered using the registration found in Stage 4." [2]) so there is no need to apply any further landmark detection algorithm. Many teams have tried it (including our team) and there was no gain compared to putting a fixed rectangular window, as I do in the code. 

Thanks,
Themos
[1] http://www.robots.ox.ac.uk/~vgg/data/lip_reading/lrw1.html
[2] http://www.robots.ox.ac.uk/~vgg/publications/2016/Chung16/chung16.pdf

**Comment by lsrock1** [comment]
Thanks for your kind reply! It is very helpful!!
